FROM node:20-alpine

WORKDIR /app
# Updated with all routes

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "dist/index.js"]
